# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'messmanager.ui'
#
# Created: Sun Feb  7 22:28:52 2016
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MessManager(object):
    def setupUi(self, MessManager):
        MessManager.setObjectName(_fromUtf8("MessManager"))
        MessManager.resize(400, 372)
        self.tabWidget = QtGui.QTabWidget(MessManager)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 401, 371))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.labelDate = QtGui.QLabel(self.tab)
        self.labelDate.setGeometry(QtCore.QRect(10, 0, 41, 21))
        self.labelDate.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.labelDate.setObjectName(_fromUtf8("labelDate"))
        self.labelUpdateMeal = QtGui.QLabel(self.tab)
        self.labelUpdateMeal.setGeometry(QtCore.QRect(10, 30, 161, 17))
        self.labelUpdateMeal.setObjectName(_fromUtf8("labelUpdateMeal"))
        self.ButtonBreakfast = QtGui.QPushButton(self.tab)
        self.ButtonBreakfast.setGeometry(QtCore.QRect(40, 50, 98, 27))
        self.ButtonBreakfast.setObjectName(_fromUtf8("ButtonBreakfast"))
        self.ButtonLunch = QtGui.QPushButton(self.tab)
        self.ButtonLunch.setGeometry(QtCore.QRect(170, 50, 98, 27))
        self.ButtonLunch.setObjectName(_fromUtf8("ButtonLunch"))
        self.ButtonDinner = QtGui.QPushButton(self.tab)
        self.ButtonDinner.setGeometry(QtCore.QRect(300, 50, 98, 27))
        self.ButtonDinner.setObjectName(_fromUtf8("ButtonDinner"))
        self.labelBreakfastIcon = QtGui.QLabel(self.tab)
        self.labelBreakfastIcon.setGeometry(QtCore.QRect(10, 50, 24, 24))
        self.labelBreakfastIcon.setText(_fromUtf8(""))
        self.labelBreakfastIcon.setPixmap(QtGui.QPixmap(_fromUtf8("breakfast3-512.png")))
        self.labelBreakfastIcon.setScaledContents(True)
        self.labelBreakfastIcon.setObjectName(_fromUtf8("labelBreakfastIcon"))
        self.labelLunchIcon = QtGui.QLabel(self.tab)
        self.labelLunchIcon.setGeometry(QtCore.QRect(140, 50, 25, 27))
        self.labelLunchIcon.setText(_fromUtf8(""))
        self.labelLunchIcon.setPixmap(QtGui.QPixmap(_fromUtf8("lunch.png")))
        self.labelLunchIcon.setScaledContents(True)
        self.labelLunchIcon.setObjectName(_fromUtf8("labelLunchIcon"))
        self.labelDinnerIcon = QtGui.QLabel(self.tab)
        self.labelDinnerIcon.setGeometry(QtCore.QRect(270, 50, 24, 24))
        self.labelDinnerIcon.setText(_fromUtf8(""))
        self.labelDinnerIcon.setPixmap(QtGui.QPixmap(_fromUtf8("dinner.png")))
        self.labelDinnerIcon.setScaledContents(True)
        self.labelDinnerIcon.setObjectName(_fromUtf8("labelDinnerIcon"))
        self.labelBazar = QtGui.QLabel(self.tab)
        self.labelBazar.setGeometry(QtCore.QRect(10, 90, 66, 17))
        self.labelBazar.setObjectName(_fromUtf8("labelBazar"))
        self.labelExpend = QtGui.QLabel(self.tab)
        self.labelExpend.setGeometry(QtCore.QRect(10, 110, 66, 17))
        self.labelExpend.setObjectName(_fromUtf8("labelExpend"))
        self.lineEditExpend = QtGui.QLineEdit(self.tab)
        self.lineEditExpend.setGeometry(QtCore.QRect(70, 106, 51, 27))
        self.lineEditExpend.setObjectName(_fromUtf8("lineEditExpend"))
        self.labelReturn = QtGui.QLabel(self.tab)
        self.labelReturn.setGeometry(QtCore.QRect(126, 110, 66, 17))
        self.labelReturn.setObjectName(_fromUtf8("labelReturn"))
        self.lineEditReturn = QtGui.QLineEdit(self.tab)
        self.lineEditReturn.setGeometry(QtCore.QRect(180, 106, 51, 27))
        self.lineEditReturn.setObjectName(_fromUtf8("lineEditReturn"))
        self.labelDeposit = QtGui.QLabel(self.tab)
        self.labelDeposit.setGeometry(QtCore.QRect(10, 140, 66, 17))
        self.labelDeposit.setObjectName(_fromUtf8("labelDeposit"))
        self.labelChosemember = QtGui.QLabel(self.tab)
        self.labelChosemember.setGeometry(QtCore.QRect(10, 160, 111, 17))
        self.labelChosemember.setObjectName(_fromUtf8("labelChosemember"))
        self.BoxMembersDeposit = QtGui.QComboBox(self.tab)
        self.BoxMembersDeposit.setGeometry(QtCore.QRect(130, 151, 101, 27))
        self.BoxMembersDeposit.setObjectName(_fromUtf8("BoxMembersDeposit"))
        self.BoxMembersDeposit.addItem(_fromUtf8(""))
        self.BoxMembersDeposit.addItem(_fromUtf8(""))
        self.BoxMembersDeposit.addItem(_fromUtf8(""))
        self.lineEditDeposit = QtGui.QLineEdit(self.tab)
        self.lineEditDeposit.setGeometry(QtCore.QRect(240, 151, 81, 27))
        self.lineEditDeposit.setObjectName(_fromUtf8("lineEditDeposit"))
        self.ButtonAdd = QtGui.QPushButton(self.tab)
        self.ButtonAdd.setGeometry(QtCore.QRect(330, 150, 61, 27))
        self.ButtonAdd.setAutoFillBackground(False)
        self.ButtonAdd.setDefault(True)
        self.ButtonAdd.setFlat(False)
        self.ButtonAdd.setObjectName(_fromUtf8("ButtonAdd"))
        self.ButtonSetBazar = QtGui.QPushButton(self.tab)
        self.ButtonSetBazar.setGeometry(QtCore.QRect(330, 105, 61, 27))
        self.ButtonSetBazar.setDefault(True)
        self.ButtonSetBazar.setObjectName(_fromUtf8("ButtonSetBazar"))
        self.dateEdit = QtGui.QDateEdit(self.tab)
        self.dateEdit.setGeometry(QtCore.QRect(50, 0, 110, 27))
        self.dateEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.BoxBazarMember = QtGui.QComboBox(self.tab)
        self.BoxBazarMember.setGeometry(QtCore.QRect(240, 106, 81, 27))
        self.BoxBazarMember.setObjectName(_fromUtf8("BoxBazarMember"))
        self.BoxBazarMember.addItem(_fromUtf8(""))
        self.BoxBazarMember.addItem(_fromUtf8(""))
        self.BoxBazarMember.addItem(_fromUtf8(""))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.MemComboOps = QtGui.QComboBox(self.tab_2)
        self.MemComboOps.setGeometry(QtCore.QRect(10, 10, 131, 27))
        self.MemComboOps.setObjectName(_fromUtf8("MemComboOps"))
        self.MemComboOps.addItem(_fromUtf8(""))
        self.MemComboOps.addItem(_fromUtf8(""))
        self.MemComboOps.addItem(_fromUtf8(""))
        self.MemComboNames = QtGui.QComboBox(self.tab_2)
        self.MemComboNames.setGeometry(QtCore.QRect(150, 10, 131, 27))
        self.MemComboNames.setObjectName(_fromUtf8("MemComboNames"))
        self.MemComboNames.addItem(_fromUtf8(""))
        self.MemComboNames.addItem(_fromUtf8(""))
        self.MemComboNames.addItem(_fromUtf8(""))
        self.pushButtonView = QtGui.QPushButton(self.tab_2)
        self.pushButtonView.setGeometry(QtCore.QRect(290, 10, 98, 27))
        self.pushButtonView.setDefault(True)
        self.pushButtonView.setObjectName(_fromUtf8("pushButtonView"))
        self.treeWidget = QtGui.QTreeWidget(self.tab_2)
        self.treeWidget.setGeometry(QtCore.QRect(10, 50, 381, 241))
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        self.treeWidget.headerItem().setText(0, _fromUtf8("1"))
        self.buttonAddmember = QtGui.QPushButton(self.tab_2)
        self.buttonAddmember.setGeometry(QtCore.QRect(50, 300, 121, 27))
        self.buttonAddmember.setDefault(True)
        self.buttonAddmember.setObjectName(_fromUtf8("buttonAddmember"))
        self.ButtonRemoveMember = QtGui.QPushButton(self.tab_2)
        self.ButtonRemoveMember.setGeometry(QtCore.QRect(200, 300, 141, 27))
        self.ButtonRemoveMember.setObjectName(_fromUtf8("ButtonRemoveMember"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        
        self.retranslateUi(MessManager)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MessManager)

    def retranslateUi(self, MessManager):
        MessManager.setWindowTitle(QtGui.QApplication.translate("MessManager", "MessManager", None, QtGui.QApplication.UnicodeUTF8))
        self.labelDate.setText(QtGui.QApplication.translate("MessManager", "Date:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelUpdateMeal.setText(QtGui.QApplication.translate("MessManager", "Update Meal For Today:", None, QtGui.QApplication.UnicodeUTF8))
        self.ButtonBreakfast.setText(QtGui.QApplication.translate("MessManager", "Breakfast", None, QtGui.QApplication.UnicodeUTF8))
        self.ButtonLunch.setText(QtGui.QApplication.translate("MessManager", "Lunch", None, QtGui.QApplication.UnicodeUTF8))
        self.ButtonDinner.setText(QtGui.QApplication.translate("MessManager", "Dinner", None, QtGui.QApplication.UnicodeUTF8))
        self.labelBazar.setText(QtGui.QApplication.translate("MessManager", "Bazar:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelExpend.setText(QtGui.QApplication.translate("MessManager", "Expend:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelReturn.setText(QtGui.QApplication.translate("MessManager", "Return:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelDeposit.setText(QtGui.QApplication.translate("MessManager", "Deposit:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelChosemember.setText(QtGui.QApplication.translate("MessManager", "Choose Member:", None, QtGui.QApplication.UnicodeUTF8))
        self.BoxMembersDeposit.setItemText(0, QtGui.QApplication.translate("MessManager", "Member1", None, QtGui.QApplication.UnicodeUTF8))
        self.BoxMembersDeposit.setItemText(1, QtGui.QApplication.translate("MessManager", "Meber2", None, QtGui.QApplication.UnicodeUTF8))
        self.BoxMembersDeposit.setItemText(2, QtGui.QApplication.translate("MessManager", "Member3", None, QtGui.QApplication.UnicodeUTF8))
        self.ButtonAdd.setText(QtGui.QApplication.translate("MessManager", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.ButtonSetBazar.setText(QtGui.QApplication.translate("MessManager", "Set", None, QtGui.QApplication.UnicodeUTF8))
        self.BoxBazarMember.setItemText(0, QtGui.QApplication.translate("MessManager", "Member1", None, QtGui.QApplication.UnicodeUTF8))
        self.BoxBazarMember.setItemText(1, QtGui.QApplication.translate("MessManager", "Member2", None, QtGui.QApplication.UnicodeUTF8))
        self.BoxBazarMember.setItemText(2, QtGui.QApplication.translate("MessManager", "Member3", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MessManager", "Operations", None, QtGui.QApplication.UnicodeUTF8))
        self.MemComboOps.setItemText(0, QtGui.QApplication.translate("MessManager", "Money", None, QtGui.QApplication.UnicodeUTF8))
        self.MemComboOps.setItemText(1, QtGui.QApplication.translate("MessManager", "Meal", None, QtGui.QApplication.UnicodeUTF8))
        self.MemComboOps.setItemText(2, QtGui.QApplication.translate("MessManager", "Bazar", None, QtGui.QApplication.UnicodeUTF8))
        self.MemComboNames.setItemText(0, QtGui.QApplication.translate("MessManager", "Member1", None, QtGui.QApplication.UnicodeUTF8))
        self.MemComboNames.setItemText(1, QtGui.QApplication.translate("MessManager", "Member2", None, QtGui.QApplication.UnicodeUTF8))
        self.MemComboNames.setItemText(2, QtGui.QApplication.translate("MessManager", "Member3", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonView.setText(QtGui.QApplication.translate("MessManager", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonAddmember.setText(QtGui.QApplication.translate("MessManager", "Add Member", None, QtGui.QApplication.UnicodeUTF8))
        self.ButtonRemoveMember.setText(QtGui.QApplication.translate("MessManager", "Remove Member", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MessManager", "Members", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("MessManager", "   Closing   ", None, QtGui.QApplication.UnicodeUTF8))
  


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MessManager = QtGui.QWidget()
    ui = Ui_MessManager()
    ui.setupUi(MessManager)
    MessManager.show()
    sys.exit(app.exec_())

